name: CI

on: [push, pull_request]

jobs:

  build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
         python-version: 3.7 
         architecture: x64
      - name: Print version
        run: python -c "import sys; print(sys.version)"

      - name: Install latest PyPI version of PyStokes 
        run: |
          python -m pip install pystokes 

      - name: Install latest PyPI version of PyRoss 
        run: |
          python -m pip install pyross

      - name: test-installation
        shell: bash -l {0}
        run: |
          python testPyRoss.py
          python testPyStokes.py

